services:
  - type: web
    name: abood-gpt-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: MISTRAL_KEY
        sync: false
    plan: free
